platform :ios do
  desc 'Export ipa and submit to TestFlight'
  lane :beta do
    keychain_info = { keychain_name: "ios-build-#{Time.now.to_i}.keychain", keychain_password: SecureRandom.uuid }

    begin
      setup_signing(keychain_info)
      bump_build_number
      build_app_with_signing(keychain_info)
      submit_to_testflight
    ensure
      cleanup_keychain(keychain_info)
    end
  end

  private_lane :setup_signing do |options|
    create_keychain(
      name: options[:keychain_name],
      password: options[:keychain_password],
      unlock: true,
      timeout: 0,
      lock_when_sleeps: false,
      add_to_search_list: true
    )
    import_cert(options)
    install_profile
    update_project_settings
  end

  lane :bump_build_number do
    file = File.read('../package.json')
    data_hash = JSON.parse(file)
    api_key = app_store_connect_api_key(
      key_id: ENV['APPLE_KEY_ID'],
      issuer_id: ENV['APPLE_ISSUER_ID'],
      key_content: ENV['APPLE_KEY_CONTENT'],
      is_key_content_base64: true,
      duration: 1200,
      in_house: false
    )
    build_num = app_store_build_number(
      api_key: api_key,
      app_identifier: ENV['BUNDLE_IDENTIFIER'],
      live: false
    )
    build_num = build_num + 1
    UI.message("Bumped build number to #{build_num}")
    increment_build_number(
      build_number: build_num,
      xcodeproj: "./ios/App/App.xcodeproj",
      skip_info_plist: true
    )
  end

  private_lane :import_cert do |options|
    cert_path = "#{Dir.tmpdir}/build_certificate.p12"
    File.write(cert_path, Base64.decode64(ENV['BUILD_CERTIFICATE_BASE64']))
    import_certificate(
      certificate_path: cert_path,
      certificate_password: ENV['P12_PASSWORD'] || "",
      keychain_name: options[:keychain_name],
      keychain_password: options[:keychain_password],
      log_output: true
    )
    File.delete(cert_path)
  end

  private_lane :cleanup_keychain do |options|
    delete_keychain(
      name: options[:keychain_name]
    )
  end

  private_lane :install_profile do
    profile_path = "#{Dir.tmpdir}/build_pp.mobileprovision"
    File.write(profile_path, Base64.decode64(ENV['BUILD_PROVISION_PROFILE_BASE64']))
    UI.user_error!("Failed to create provisioning profile at #{profile_path}") unless File.exist?(profile_path)
    ENV['PROVISIONING_PROFILE_PATH'] = profile_path
    install_provisioning_profile(path: profile_path)
    File.delete(profile_path)
  end

  private_lane :update_project_settings do
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "./ios/App/App.xcodeproj",
      code_sign_identity: "iPhone Distribution",
      profile_name: ENV['APPLE_PROFILE_NAME'],
      bundle_identifier: ENV['BUNDLE_IDENTIFIER'],
      team_id: ENV['APP_STORE_CONNECT_TEAM_ID']
    )
    update_project_team(
      path: "./ios/App/App.xcodeproj",
      teamid: ENV['APP_STORE_CONNECT_TEAM_ID']
    )
  end

  private_lane :build_app_with_signing do |options|
    unlock_keychain(
      path: options[:keychain_name],
      password: options[:keychain_password],
      set_default: false
    )
    build_app(
      workspace: "./ios/App/App.xcworkspace",
      scheme: "PyCon US",
      configuration: "Release",
      export_method: "app-store",
      output_name: "App.ipa",
      export_options: {
        provisioningProfiles: {
          ENV['BUNDLE_IDENTIFIER'] => ENV['APPLE_PROFILE_NAME']
        }
      },
      xcargs: "-verbose",
      buildlog_path: "./build_logs",
      export_xcargs: "-allowProvisioningUpdates",
    )
  end

#   private_lane :submit_to_testflight do
#     api_key = app_store_connect_api_key(
#       key_id: ENV['APPLE_KEY_ID'],
#       issuer_id: ENV['APPLE_ISSUER_ID'],
#       key_content: ENV['APPLE_KEY_CONTENT'],
#       is_key_content_base64: true,
#       duration: 1200,
#       in_house: false
#     )
#     pilot(
#       api_key: api_key,
#       skip_waiting_for_build_processing: true,
#       skip_submission: true,
#       distribute_external: false,
#       notify_external_testers: false,
#       ipa: "./App.ipa"
#     )
#   end
end

KEYSTORE_KEY_ALIAS = ENV["KEYSTORE_KEY_ALIAS"]
KEYSTORE_KEY_PASSWORD = ENV["KEYSTORE_KEY_PASSWORD"]
KEYSTORE_STORE_PASSWORD = ENV["KEYSTORE_STORE_PASSWORD"]

platform :android do
  desc "Deploy a beta version to the Google Play"

  private_lane :verify_changelog_exists do |version_code:|
    changelog_path = "android/metadata/en-US/changelogs/#{version_code}.txt"
    UI.user_error!("Missing changelog file at #{changelog_path}") unless File.exist?(changelog_path)
    UI.message("Changelog exists for version code #{version_code}")
  end

  private_lane :verify_upload_to_staging do |version_name:|
    UI.message "Skipping staging verification step"
  end

  lane :beta do
    keystore_path = "#{Dir.tmpdir}/build_keystore.keystore"
    File.write(keystore_path, Base64.decode64(ENV['ANDROID_KEYSTORE_FILE']))
    json_key_data = Base64.decode64(ENV['PLAY_CONFIG_JSON'])

    # Get previous build number and increment
    previous_build_number = google_play_track_version_codes(
      package_name: ENV['DEVELOPER_PACKAGE_NAME'],
      track: "internal",
      json_key_data: json_key_data,
    )[0]
    current_build_number = previous_build_number + 1
    sh("export NEW_BUILD_NUMBER=#{current_build_number}")

    # Build the app
    gradle(
      task: "clean bundleRelease",
      project_dir: 'android/',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => "#{keystore_path}",
        "android.injected.signing.store.password" => "#{KEYSTORE_STORE_PASSWORD}",
        "android.injected.signing.key.alias" => "#{KEYSTORE_KEY_ALIAS}",
        "android.injected.signing.key.password" => "#{KEYSTORE_KEY_PASSWORD}",
        'versionCode' => current_build_number
      })

    # Upload to Play Store
#     upload_to_play_store(
#       package_name: ENV['DEVELOPER_PACKAGE_NAME'],
#       json_key_data: json_key_data,
#       track: 'internal',
#       release_status: 'completed',
#       skip_upload_metadata: true,
#       skip_upload_changelogs: true,
#       skip_upload_images: true,
#       skip_upload_screenshots: true,
#     )
  end
end
